-- Check FeedInventory columns
SELECT 'FeedInventory' as TableName, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'FeedInventory'
ORDER BY ORDINAL_POSITION;

-- Check ChemicalInventory columns
SELECT 'ChemicalInventory' as TableName, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ChemicalInventory'
ORDER BY ORDINAL_POSITION;

-- Check FeedLedger columns
SELECT 'FeedLedger' as TableName, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'FeedLedger'
ORDER BY ORDINAL_POSITION;

-- Check ChemicalLedger columns
SELECT 'ChemicalLedger' as TableName, COLUMN_NAME, DATA_TYPE, IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'ChemicalLedger'
ORDER BY ORDINAL_POSITION;
